/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_APP_V1_MAIN_PB_H_INCLUDED
#define PB_APP_V1_MAIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _app_v1_ClientType {
    app_v1_ClientType_STUDENT_READER = 0,
    app_v1_ClientType_VEHICLE_READER = 1
} app_v1_ClientType;

/* Struct definitions */
typedef struct _app_v1_StudentDepartureMessage {
    /* Timestamp in milliseconds */
    uint64_t timestamp;
    pb_callback_t tagId;
} app_v1_StudentDepartureMessage;

typedef struct _app_v1_VehicleArrivalMessage {
    /* Timestamp in milliseconds */
    uint64_t timestamp;
    pb_callback_t tagId;
} app_v1_VehicleArrivalMessage;

typedef struct _app_v1_ReaderStatusMessage {
    bool isOnline;
    /* Timestamp in milliseconds */
    bool has_timestamp;
    uint64_t timestamp;
    pb_callback_t clientId;
    pb_callback_t firmwareVersion;
    pb_callback_t clientInfo;
} app_v1_ReaderStatusMessage;

typedef struct _app_v1_SetupInitMessage {
    uint64_t timestamp;
    pb_callback_t clientId;
    pb_callback_t firmwareVersion;
    pb_callback_t clientInfo;
    app_v1_ClientType clientType;
} app_v1_SetupInitMessage;

typedef struct _app_v1_SetupConfigureMessage {
    pb_callback_t username;
    pb_callback_t password;
} app_v1_SetupConfigureMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _app_v1_ClientType_MIN app_v1_ClientType_STUDENT_READER
#define _app_v1_ClientType_MAX app_v1_ClientType_VEHICLE_READER
#define _app_v1_ClientType_ARRAYSIZE ((app_v1_ClientType)(app_v1_ClientType_VEHICLE_READER+1))




#define app_v1_SetupInitMessage_clientType_ENUMTYPE app_v1_ClientType



/* Initializer values for message structs */
#define app_v1_StudentDepartureMessage_init_default {0, {{NULL}, NULL}}
#define app_v1_VehicleArrivalMessage_init_default {0, {{NULL}, NULL}}
#define app_v1_ReaderStatusMessage_init_default  {0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define app_v1_SetupInitMessage_init_default     {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _app_v1_ClientType_MIN}
#define app_v1_SetupConfigureMessage_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define app_v1_StudentDepartureMessage_init_zero {0, {{NULL}, NULL}}
#define app_v1_VehicleArrivalMessage_init_zero   {0, {{NULL}, NULL}}
#define app_v1_ReaderStatusMessage_init_zero     {0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define app_v1_SetupInitMessage_init_zero        {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _app_v1_ClientType_MIN}
#define app_v1_SetupConfigureMessage_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define app_v1_StudentDepartureMessage_timestamp_tag 1
#define app_v1_StudentDepartureMessage_tagId_tag 2
#define app_v1_VehicleArrivalMessage_timestamp_tag 1
#define app_v1_VehicleArrivalMessage_tagId_tag   2
#define app_v1_ReaderStatusMessage_isOnline_tag  1
#define app_v1_ReaderStatusMessage_timestamp_tag 2
#define app_v1_ReaderStatusMessage_clientId_tag  3
#define app_v1_ReaderStatusMessage_firmwareVersion_tag 4
#define app_v1_ReaderStatusMessage_clientInfo_tag 5
#define app_v1_SetupInitMessage_timestamp_tag    1
#define app_v1_SetupInitMessage_clientId_tag     2
#define app_v1_SetupInitMessage_firmwareVersion_tag 3
#define app_v1_SetupInitMessage_clientInfo_tag   4
#define app_v1_SetupInitMessage_clientType_tag   5
#define app_v1_SetupConfigureMessage_username_tag 1
#define app_v1_SetupConfigureMessage_password_tag 2

/* Struct field encoding specification for nanopb */
#define app_v1_StudentDepartureMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, CALLBACK, SINGULAR, BYTES,    tagId,             2)
#define app_v1_StudentDepartureMessage_CALLBACK pb_default_field_callback
#define app_v1_StudentDepartureMessage_DEFAULT NULL

#define app_v1_VehicleArrivalMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, CALLBACK, SINGULAR, BYTES,    tagId,             2)
#define app_v1_VehicleArrivalMessage_CALLBACK pb_default_field_callback
#define app_v1_VehicleArrivalMessage_DEFAULT NULL

#define app_v1_ReaderStatusMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     isOnline,          1) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         2) \
X(a, CALLBACK, OPTIONAL, STRING,   clientId,          3) \
X(a, CALLBACK, OPTIONAL, STRING,   firmwareVersion,   4) \
X(a, CALLBACK, OPTIONAL, STRING,   clientInfo,        5)
#define app_v1_ReaderStatusMessage_CALLBACK pb_default_field_callback
#define app_v1_ReaderStatusMessage_DEFAULT NULL

#define app_v1_SetupInitMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, CALLBACK, SINGULAR, STRING,   clientId,          2) \
X(a, CALLBACK, SINGULAR, STRING,   firmwareVersion,   3) \
X(a, CALLBACK, SINGULAR, STRING,   clientInfo,        4) \
X(a, STATIC,   SINGULAR, UENUM,    clientType,        5)
#define app_v1_SetupInitMessage_CALLBACK pb_default_field_callback
#define app_v1_SetupInitMessage_DEFAULT NULL

#define app_v1_SetupConfigureMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   username,          1) \
X(a, CALLBACK, SINGULAR, STRING,   password,          2)
#define app_v1_SetupConfigureMessage_CALLBACK pb_default_field_callback
#define app_v1_SetupConfigureMessage_DEFAULT NULL

extern const pb_msgdesc_t app_v1_StudentDepartureMessage_msg;
extern const pb_msgdesc_t app_v1_VehicleArrivalMessage_msg;
extern const pb_msgdesc_t app_v1_ReaderStatusMessage_msg;
extern const pb_msgdesc_t app_v1_SetupInitMessage_msg;
extern const pb_msgdesc_t app_v1_SetupConfigureMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define app_v1_StudentDepartureMessage_fields &app_v1_StudentDepartureMessage_msg
#define app_v1_VehicleArrivalMessage_fields &app_v1_VehicleArrivalMessage_msg
#define app_v1_ReaderStatusMessage_fields &app_v1_ReaderStatusMessage_msg
#define app_v1_SetupInitMessage_fields &app_v1_SetupInitMessage_msg
#define app_v1_SetupConfigureMessage_fields &app_v1_SetupConfigureMessage_msg

/* Maximum encoded size of messages (where known) */
/* app_v1_StudentDepartureMessage_size depends on runtime parameters */
/* app_v1_VehicleArrivalMessage_size depends on runtime parameters */
/* app_v1_ReaderStatusMessage_size depends on runtime parameters */
/* app_v1_SetupInitMessage_size depends on runtime parameters */
/* app_v1_SetupConfigureMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
