/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "main.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(app_v1_StudentDepartureMessage, app_v1_StudentDepartureMessage, AUTO)


PB_BIND(app_v1_VehicleArrivalMessage, app_v1_VehicleArrivalMessage, AUTO)


PB_BIND(app_v1_ReaderStatusMessage, app_v1_ReaderStatusMessage, AUTO)


PB_BIND(app_v1_SetupInitMessage, app_v1_SetupInitMessage, AUTO)


PB_BIND(app_v1_SetupConfigureMessage, app_v1_SetupConfigureMessage, AUTO)





