# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x06\x61pp.v1\";\n\x17StudentDepartureMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05tagId\x18\x02 \x01(\x0c\"9\n\x15VehicleArrivalMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05tagId\x18\x02 \x01(\x0c\"q\n\x13ReaderStatusMessage\x12\x10\n\x08isOnline\x18\x01 \x01(\x08\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08\x63lientId\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_timestampB\x0b\n\t_clientIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENTDEPARTUREMESSAGE']._serialized_start=22
  _globals['_STUDENTDEPARTUREMESSAGE']._serialized_end=81
  _globals['_VEHICLEARRIVALMESSAGE']._serialized_start=83
  _globals['_VEHICLEARRIVALMESSAGE']._serialized_end=140
  _globals['_READERSTATUSMESSAGE']._serialized_start=142
  _globals['_READERSTATUSMESSAGE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
